### ISSUE TITLE
Bug：当 Bot 同时存在于多个群时，Bot 只会向其中一个群广播

### ISSUE THREAD

**Issue by CatMe0w** [czp3009/bilibili-live-notification-telegram-bot#2]
具体表现：我将运行该程序的 Bot 拉入了两个群（ [如图所示](https://imgur.com/a/JCxRTEq) ），但 Bot 只会固定向前一个群广播 Bilibili 直播状态的变更。
但两个群都能响应 /enable 等指令。

由于我没有将软件的运行 Log 单独输出到文件，因此只能（从终端）获取到部分 Log， 如下：
https://pastebin.com/RjRJ0AfW

**Comment by czp3009** [comment]
已修复此问题
